package com.cn.web.school.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AttendanceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	protected int start = -1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	protected int limit = -1;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public AttendanceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public void setStart(int start) {
		this.start = start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public int getStart() {
		return start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public void setLimit(int limit) {
		this.limit = limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public int getLimit() {
		return limit;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeIsNull() {
			addCriterion("schedule_code is null");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeIsNotNull() {
			addCriterion("schedule_code is not null");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeEqualTo(String value) {
			addCriterion("schedule_code =", value, "scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeNotEqualTo(String value) {
			addCriterion("schedule_code <>", value, "scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeGreaterThan(String value) {
			addCriterion("schedule_code >", value, "scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeGreaterThanOrEqualTo(String value) {
			addCriterion("schedule_code >=", value, "scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeLessThan(String value) {
			addCriterion("schedule_code <", value, "scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeLessThanOrEqualTo(String value) {
			addCriterion("schedule_code <=", value, "scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeLike(String value) {
			addCriterion("schedule_code like", value, "scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeNotLike(String value) {
			addCriterion("schedule_code not like", value, "scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeIn(List<String> values) {
			addCriterion("schedule_code in", values, "scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeNotIn(List<String> values) {
			addCriterion("schedule_code not in", values, "scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeBetween(String value1, String value2) {
			addCriterion("schedule_code between", value1, value2,
					"scheduleCode");
			return (Criteria) this;
		}

		public Criteria andScheduleCodeNotBetween(String value1, String value2) {
			addCriterion("schedule_code not between", value1, value2,
					"scheduleCode");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNull() {
			addCriterion("longitude is null");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNotNull() {
			addCriterion("longitude is not null");
			return (Criteria) this;
		}

		public Criteria andLongitudeEqualTo(String value) {
			addCriterion("longitude =", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotEqualTo(String value) {
			addCriterion("longitude <>", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThan(String value) {
			addCriterion("longitude >", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
			addCriterion("longitude >=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThan(String value) {
			addCriterion("longitude <", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThanOrEqualTo(String value) {
			addCriterion("longitude <=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLike(String value) {
			addCriterion("longitude like", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotLike(String value) {
			addCriterion("longitude not like", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeIn(List<String> values) {
			addCriterion("longitude in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotIn(List<String> values) {
			addCriterion("longitude not in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeBetween(String value1, String value2) {
			addCriterion("longitude between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotBetween(String value1, String value2) {
			addCriterion("longitude not between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNull() {
			addCriterion("latitude is null");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNotNull() {
			addCriterion("latitude is not null");
			return (Criteria) this;
		}

		public Criteria andLatitudeEqualTo(String value) {
			addCriterion("latitude =", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotEqualTo(String value) {
			addCriterion("latitude <>", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThan(String value) {
			addCriterion("latitude >", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
			addCriterion("latitude >=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThan(String value) {
			addCriterion("latitude <", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThanOrEqualTo(String value) {
			addCriterion("latitude <=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLike(String value) {
			addCriterion("latitude like", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotLike(String value) {
			addCriterion("latitude not like", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeIn(List<String> values) {
			addCriterion("latitude in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotIn(List<String> values) {
			addCriterion("latitude not in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeBetween(String value1, String value2) {
			addCriterion("latitude between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotBetween(String value1, String value2) {
			addCriterion("latitude not between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andStartIsNull() {
			addCriterion("start is null");
			return (Criteria) this;
		}

		public Criteria andStartIsNotNull() {
			addCriterion("start is not null");
			return (Criteria) this;
		}

		public Criteria andStartEqualTo(Date value) {
			addCriterion("start =", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotEqualTo(Date value) {
			addCriterion("start <>", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartGreaterThan(Date value) {
			addCriterion("start >", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartGreaterThanOrEqualTo(Date value) {
			addCriterion("start >=", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartLessThan(Date value) {
			addCriterion("start <", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartLessThanOrEqualTo(Date value) {
			addCriterion("start <=", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartIn(List<Date> values) {
			addCriterion("start in", values, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotIn(List<Date> values) {
			addCriterion("start not in", values, "start");
			return (Criteria) this;
		}

		public Criteria andStartBetween(Date value1, Date value2) {
			addCriterion("start between", value1, value2, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotBetween(Date value1, Date value2) {
			addCriterion("start not between", value1, value2, "start");
			return (Criteria) this;
		}

		public Criteria andEndIsNull() {
			addCriterion("end is null");
			return (Criteria) this;
		}

		public Criteria andEndIsNotNull() {
			addCriterion("end is not null");
			return (Criteria) this;
		}

		public Criteria andEndEqualTo(Date value) {
			addCriterion("end =", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotEqualTo(Date value) {
			addCriterion("end <>", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndGreaterThan(Date value) {
			addCriterion("end >", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndGreaterThanOrEqualTo(Date value) {
			addCriterion("end >=", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLessThan(Date value) {
			addCriterion("end <", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLessThanOrEqualTo(Date value) {
			addCriterion("end <=", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndIn(List<Date> values) {
			addCriterion("end in", values, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotIn(List<Date> values) {
			addCriterion("end not in", values, "end");
			return (Criteria) this;
		}

		public Criteria andEndBetween(Date value1, Date value2) {
			addCriterion("end between", value1, value2, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotBetween(Date value1, Date value2) {
			addCriterion("end not between", value1, value2, "end");
			return (Criteria) this;
		}

		public Criteria andDeviationIsNull() {
			addCriterion("deviation is null");
			return (Criteria) this;
		}

		public Criteria andDeviationIsNotNull() {
			addCriterion("deviation is not null");
			return (Criteria) this;
		}

		public Criteria andDeviationEqualTo(String value) {
			addCriterion("deviation =", value, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationNotEqualTo(String value) {
			addCriterion("deviation <>", value, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationGreaterThan(String value) {
			addCriterion("deviation >", value, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationGreaterThanOrEqualTo(String value) {
			addCriterion("deviation >=", value, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationLessThan(String value) {
			addCriterion("deviation <", value, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationLessThanOrEqualTo(String value) {
			addCriterion("deviation <=", value, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationLike(String value) {
			addCriterion("deviation like", value, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationNotLike(String value) {
			addCriterion("deviation not like", value, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationIn(List<String> values) {
			addCriterion("deviation in", values, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationNotIn(List<String> values) {
			addCriterion("deviation not in", values, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationBetween(String value1, String value2) {
			addCriterion("deviation between", value1, value2, "deviation");
			return (Criteria) this;
		}

		public Criteria andDeviationNotBetween(String value1, String value2) {
			addCriterion("deviation not between", value1, value2, "deviation");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeIsNull() {
			addCriterion("teacher_code is null");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeIsNotNull() {
			addCriterion("teacher_code is not null");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeEqualTo(String value) {
			addCriterion("teacher_code =", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeNotEqualTo(String value) {
			addCriterion("teacher_code <>", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeGreaterThan(String value) {
			addCriterion("teacher_code >", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeGreaterThanOrEqualTo(String value) {
			addCriterion("teacher_code >=", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeLessThan(String value) {
			addCriterion("teacher_code <", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeLessThanOrEqualTo(String value) {
			addCriterion("teacher_code <=", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeLike(String value) {
			addCriterion("teacher_code like", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeNotLike(String value) {
			addCriterion("teacher_code not like", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeIn(List<String> values) {
			addCriterion("teacher_code in", values, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeNotIn(List<String> values) {
			addCriterion("teacher_code not in", values, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeBetween(String value1, String value2) {
			addCriterion("teacher_code between", value1, value2, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeNotBetween(String value1, String value2) {
			addCriterion("teacher_code not between", value1, value2,
					"teacherCode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeIsNull() {
			addCriterion("attendcode is null");
			return (Criteria) this;
		}

		public Criteria andAttendcodeIsNotNull() {
			addCriterion("attendcode is not null");
			return (Criteria) this;
		}

		public Criteria andAttendcodeEqualTo(String value) {
			addCriterion("attendcode =", value, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeNotEqualTo(String value) {
			addCriterion("attendcode <>", value, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeGreaterThan(String value) {
			addCriterion("attendcode >", value, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeGreaterThanOrEqualTo(String value) {
			addCriterion("attendcode >=", value, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeLessThan(String value) {
			addCriterion("attendcode <", value, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeLessThanOrEqualTo(String value) {
			addCriterion("attendcode <=", value, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeLike(String value) {
			addCriterion("attendcode like", value, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeNotLike(String value) {
			addCriterion("attendcode not like", value, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeIn(List<String> values) {
			addCriterion("attendcode in", values, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeNotIn(List<String> values) {
			addCriterion("attendcode not in", values, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeBetween(String value1, String value2) {
			addCriterion("attendcode between", value1, value2, "attendcode");
			return (Criteria) this;
		}

		public Criteria andAttendcodeNotBetween(String value1, String value2) {
			addCriterion("attendcode not between", value1, value2, "attendcode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeIsNull() {
			addCriterion("school_code is null");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeIsNotNull() {
			addCriterion("school_code is not null");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeEqualTo(String value) {
			addCriterion("school_code =", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeNotEqualTo(String value) {
			addCriterion("school_code <>", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeGreaterThan(String value) {
			addCriterion("school_code >", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeGreaterThanOrEqualTo(String value) {
			addCriterion("school_code >=", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeLessThan(String value) {
			addCriterion("school_code <", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeLessThanOrEqualTo(String value) {
			addCriterion("school_code <=", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeLike(String value) {
			addCriterion("school_code like", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeNotLike(String value) {
			addCriterion("school_code not like", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeIn(List<String> values) {
			addCriterion("school_code in", values, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeNotIn(List<String> values) {
			addCriterion("school_code not in", values, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeBetween(String value1, String value2) {
			addCriterion("school_code between", value1, value2, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeNotBetween(String value1, String value2) {
			addCriterion("school_code not between", value1, value2,
					"schoolCode");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attendance
     *
     * @mbggenerated do_not_delete_during_merge Sat Jan 23 11:24:53 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}