package com.cn.web.school.po;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.student_code
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    private String studentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.schedul_code
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    private String schedulCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.longitude
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.latitude
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.valid
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    private String valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.attendcode
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    private String attendcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.student_code
     *
     * @return the value of record.student_code
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public String getStudentCode() {
        return studentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.student_code
     *
     * @param studentCode the value for record.student_code
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.schedul_code
     *
     * @return the value of record.schedul_code
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public String getSchedulCode() {
        return schedulCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.schedul_code
     *
     * @param schedulCode the value for record.schedul_code
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public void setSchedulCode(String schedulCode) {
        this.schedulCode = schedulCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.longitude
     *
     * @return the value of record.longitude
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.longitude
     *
     * @param longitude the value for record.longitude
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.latitude
     *
     * @return the value of record.latitude
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.latitude
     *
     * @param latitude the value for record.latitude
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time
     *
     * @return the value of record.time
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time
     *
     * @param time the value for record.time
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.valid
     *
     * @return the value of record.valid
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.valid
     *
     * @param valid the value for record.valid
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public void setValid(String valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.attendcode
     *
     * @return the value of record.attendcode
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public String getAttendcode() {
        return attendcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.attendcode
     *
     * @param attendcode the value for record.attendcode
     *
     * @mbggenerated Tue Jan 26 11:05:59 CST 2016
     */
    public void setAttendcode(String attendcode) {
        this.attendcode = attendcode;
    }
}