package com.cn.web.school.po;
/** * @author  作者 :ZJUT Shanghq 
 * @date 创建时间：2016年4月10日 下午9:30:53
 * @version 1.0 
 */
public class ScheduleList {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.id
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.code
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.name
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.time
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	private String time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.site
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	private String site;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.school_code
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	private String schoolCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.teacher_code
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	private String teacherCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.period
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	private String period;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.credit
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	private String credit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.start
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */

	private String start;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.end
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */

	private String end;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.id
	 * @return  the value of schedule.id
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.id
	 * @param id  the value for schedule.id
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.code
	 * @return  the value of schedule.code
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.code
	 * @param code  the value for schedule.code
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.name
	 * @return  the value of schedule.name
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.name
	 * @param name  the value for schedule.name
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.time
	 * @return  the value of schedule.time
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.time
	 * @param time  the value for schedule.time
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.site
	 * @return  the value of schedule.site
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getSite() {
		return site;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.site
	 * @param site  the value for schedule.site
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setSite(String site) {
		this.site = site;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.school_code
	 * @return  the value of schedule.school_code
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getSchoolCode() {
		return schoolCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.school_code
	 * @param schoolCode  the value for schedule.school_code
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setSchoolCode(String schoolCode) {
		this.schoolCode = schoolCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.teacher_code
	 * @return  the value of schedule.teacher_code
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getTeacherCode() {
		return teacherCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.teacher_code
	 * @param teacherCode  the value for schedule.teacher_code
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setTeacherCode(String teacherCode) {
		this.teacherCode = teacherCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.period
	 * @return  the value of schedule.period
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.period
	 * @param period  the value for schedule.period
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setPeriod(String period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.credit
	 * @return  the value of schedule.credit
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getCredit() {
		return credit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.credit
	 * @param credit  the value for schedule.credit
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setCredit(String credit) {
		this.credit = credit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.start
	 * @return  the value of schedule.start
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getStart() {
		return start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.start
	 * @param start  the value for schedule.start
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */

	public void setStart(String start) {
		this.start = start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.end
	 * @return  the value of schedule.end
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getEnd() {
		return end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.end
	 * @param end  the value for schedule.end
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */

	public void setEnd(String end) {
		this.end = end;
	}
}