package com.cn.web.school.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ScheduleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	protected int start = -1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	protected int limit = -1;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public ScheduleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setStart(int start) {
		this.start = start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public int getStart() {
		return start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public void setLimit(int limit) {
		this.limit = limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public int getLimit() {
		return limit;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCTime(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Time(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCTime(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				timeList.add(new java.sql.Time(iter.next().getTime()));
			}
			addCriterion(condition, timeList, property);
		}

		protected void addCriterionForJDBCTime(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Time(value1.getTime()),
					new java.sql.Time(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(String value) {
			addCriterion("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(String value) {
			addCriterion("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(String value) {
			addCriterion("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(String value) {
			addCriterion("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(String value) {
			addCriterion("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(String value) {
			addCriterion("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLike(String value) {
			addCriterion("time like", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotLike(String value) {
			addCriterion("time not like", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<String> values) {
			addCriterion("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<String> values) {
			addCriterion("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(String value1, String value2) {
			addCriterion("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(String value1, String value2) {
			addCriterion("time not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andSiteIsNull() {
			addCriterion("site is null");
			return (Criteria) this;
		}

		public Criteria andSiteIsNotNull() {
			addCriterion("site is not null");
			return (Criteria) this;
		}

		public Criteria andSiteEqualTo(String value) {
			addCriterion("site =", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotEqualTo(String value) {
			addCriterion("site <>", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteGreaterThan(String value) {
			addCriterion("site >", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteGreaterThanOrEqualTo(String value) {
			addCriterion("site >=", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLessThan(String value) {
			addCriterion("site <", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLessThanOrEqualTo(String value) {
			addCriterion("site <=", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLike(String value) {
			addCriterion("site like", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotLike(String value) {
			addCriterion("site not like", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteIn(List<String> values) {
			addCriterion("site in", values, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotIn(List<String> values) {
			addCriterion("site not in", values, "site");
			return (Criteria) this;
		}

		public Criteria andSiteBetween(String value1, String value2) {
			addCriterion("site between", value1, value2, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotBetween(String value1, String value2) {
			addCriterion("site not between", value1, value2, "site");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeIsNull() {
			addCriterion("school_code is null");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeIsNotNull() {
			addCriterion("school_code is not null");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeEqualTo(String value) {
			addCriterion("school_code =", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeNotEqualTo(String value) {
			addCriterion("school_code <>", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeGreaterThan(String value) {
			addCriterion("school_code >", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeGreaterThanOrEqualTo(String value) {
			addCriterion("school_code >=", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeLessThan(String value) {
			addCriterion("school_code <", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeLessThanOrEqualTo(String value) {
			addCriterion("school_code <=", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeLike(String value) {
			addCriterion("school_code like", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeNotLike(String value) {
			addCriterion("school_code not like", value, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeIn(List<String> values) {
			addCriterion("school_code in", values, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeNotIn(List<String> values) {
			addCriterion("school_code not in", values, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeBetween(String value1, String value2) {
			addCriterion("school_code between", value1, value2, "schoolCode");
			return (Criteria) this;
		}

		public Criteria andSchoolCodeNotBetween(String value1, String value2) {
			addCriterion("school_code not between", value1, value2,
					"schoolCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeIsNull() {
			addCriterion("teacher_code is null");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeIsNotNull() {
			addCriterion("teacher_code is not null");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeEqualTo(String value) {
			addCriterion("teacher_code =", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeNotEqualTo(String value) {
			addCriterion("teacher_code <>", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeGreaterThan(String value) {
			addCriterion("teacher_code >", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeGreaterThanOrEqualTo(String value) {
			addCriterion("teacher_code >=", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeLessThan(String value) {
			addCriterion("teacher_code <", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeLessThanOrEqualTo(String value) {
			addCriterion("teacher_code <=", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeLike(String value) {
			addCriterion("teacher_code like", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeNotLike(String value) {
			addCriterion("teacher_code not like", value, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeIn(List<String> values) {
			addCriterion("teacher_code in", values, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeNotIn(List<String> values) {
			addCriterion("teacher_code not in", values, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeBetween(String value1, String value2) {
			addCriterion("teacher_code between", value1, value2, "teacherCode");
			return (Criteria) this;
		}

		public Criteria andTeacherCodeNotBetween(String value1, String value2) {
			addCriterion("teacher_code not between", value1, value2,
					"teacherCode");
			return (Criteria) this;
		}

		public Criteria andPeriodIsNull() {
			addCriterion("period is null");
			return (Criteria) this;
		}

		public Criteria andPeriodIsNotNull() {
			addCriterion("period is not null");
			return (Criteria) this;
		}

		public Criteria andPeriodEqualTo(String value) {
			addCriterion("period =", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodNotEqualTo(String value) {
			addCriterion("period <>", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodGreaterThan(String value) {
			addCriterion("period >", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodGreaterThanOrEqualTo(String value) {
			addCriterion("period >=", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodLessThan(String value) {
			addCriterion("period <", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodLessThanOrEqualTo(String value) {
			addCriterion("period <=", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodLike(String value) {
			addCriterion("period like", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodNotLike(String value) {
			addCriterion("period not like", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodIn(List<String> values) {
			addCriterion("period in", values, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodNotIn(List<String> values) {
			addCriterion("period not in", values, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodBetween(String value1, String value2) {
			addCriterion("period between", value1, value2, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodNotBetween(String value1, String value2) {
			addCriterion("period not between", value1, value2, "period");
			return (Criteria) this;
		}

		public Criteria andCreditIsNull() {
			addCriterion("credit is null");
			return (Criteria) this;
		}

		public Criteria andCreditIsNotNull() {
			addCriterion("credit is not null");
			return (Criteria) this;
		}

		public Criteria andCreditEqualTo(String value) {
			addCriterion("credit =", value, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditNotEqualTo(String value) {
			addCriterion("credit <>", value, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditGreaterThan(String value) {
			addCriterion("credit >", value, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditGreaterThanOrEqualTo(String value) {
			addCriterion("credit >=", value, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditLessThan(String value) {
			addCriterion("credit <", value, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditLessThanOrEqualTo(String value) {
			addCriterion("credit <=", value, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditLike(String value) {
			addCriterion("credit like", value, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditNotLike(String value) {
			addCriterion("credit not like", value, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditIn(List<String> values) {
			addCriterion("credit in", values, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditNotIn(List<String> values) {
			addCriterion("credit not in", values, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditBetween(String value1, String value2) {
			addCriterion("credit between", value1, value2, "credit");
			return (Criteria) this;
		}

		public Criteria andCreditNotBetween(String value1, String value2) {
			addCriterion("credit not between", value1, value2, "credit");
			return (Criteria) this;
		}

		public Criteria andStartIsNull() {
			addCriterion("start is null");
			return (Criteria) this;
		}

		public Criteria andStartIsNotNull() {
			addCriterion("start is not null");
			return (Criteria) this;
		}

		public Criteria andStartEqualTo(Date value) {
			addCriterionForJDBCTime("start =", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotEqualTo(Date value) {
			addCriterionForJDBCTime("start <>", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartGreaterThan(Date value) {
			addCriterionForJDBCTime("start >", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("start >=", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartLessThan(Date value) {
			addCriterionForJDBCTime("start <", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("start <=", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartIn(List<Date> values) {
			addCriterionForJDBCTime("start in", values, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotIn(List<Date> values) {
			addCriterionForJDBCTime("start not in", values, "start");
			return (Criteria) this;
		}

		public Criteria andStartBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("start between", value1, value2, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("start not between", value1, value2,
					"start");
			return (Criteria) this;
		}

		public Criteria andEndIsNull() {
			addCriterion("end is null");
			return (Criteria) this;
		}

		public Criteria andEndIsNotNull() {
			addCriterion("end is not null");
			return (Criteria) this;
		}

		public Criteria andEndEqualTo(Date value) {
			addCriterionForJDBCTime("end =", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotEqualTo(Date value) {
			addCriterionForJDBCTime("end <>", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndGreaterThan(Date value) {
			addCriterionForJDBCTime("end >", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("end >=", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLessThan(Date value) {
			addCriterionForJDBCTime("end <", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("end <=", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndIn(List<Date> values) {
			addCriterionForJDBCTime("end in", values, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotIn(List<Date> values) {
			addCriterionForJDBCTime("end not in", values, "end");
			return (Criteria) this;
		}

		public Criteria andEndBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("end between", value1, value2, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("end not between", value1, value2, "end");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 20 16:32:18 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}