package com.cn.web.school.po;

public class Subject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.id
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.student_code
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    private String studentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.schedule_code
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    private String scheduleCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.id
     *
     * @return the value of subject.id
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.id
     *
     * @param id the value for subject.id
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.student_code
     *
     * @return the value of subject.student_code
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    public String getStudentCode() {
        return studentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.student_code
     *
     * @param studentCode the value for subject.student_code
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.schedule_code
     *
     * @return the value of subject.schedule_code
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    public String getScheduleCode() {
        return scheduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.schedule_code
     *
     * @param scheduleCode the value for subject.schedule_code
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    public void setScheduleCode(String scheduleCode) {
        this.scheduleCode = scheduleCode;
    }
}