package com.cn.web.school.dao;

import com.cn.web.school.po.Attendance;
import com.cn.web.school.po.AttendanceExample;
import com.cn.web.school.po.Schedule;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AttendanceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	int countByExample(AttendanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	int deleteByExample(AttendanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	int insert(Attendance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	int insertSelective(Attendance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	List<Attendance> selectByExample(AttendanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	Attendance selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Attendance record,
			@Param("example") AttendanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	int updateByExample(@Param("record") Attendance record,
			@Param("example") AttendanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	int updateByPrimaryKeySelective(Attendance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Sun Jan 24 13:08:21 CST 2016
	 */
	int updateByPrimaryKey(Attendance record);


	List<Attendance> selectAllByteacherCode(String code);

	String selectDayByTime(Attendance attendance);

	List<Attendance> selectByattendcode(Attendance attendance);

	Attendance seletBycode(String attendcode);
}