package com.cn.web.school.dao;

import com.cn.web.school.po.Schedule;
import com.cn.web.school.po.ScheduleExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ScheduleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	int countByExample(ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	int deleteByExample(ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	int insert(Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	int insertSelective(Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	List<Schedule> selectByExample(ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	Schedule selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Schedule record,
			@Param("example") ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	int updateByExample(@Param("record") Schedule record,
			@Param("example") ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	int updateByPrimaryKeySelective(Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbggenerated  Fri Jan 22 08:07:31 CST 2016
	 */
	int updateByPrimaryKey(Schedule record);

	List<String> selectcodeBycheck(Schedule schedule);

	Schedule selectAllBycheck(Schedule schedule);

	List<Schedule> selectAllByteacherCode(String teacherCode);

	List<String> selectcodeBytimecheck(Schedule schedule);

	List<Schedule> selectInforByCode(Schedule b1);

	List<String> selectclasscodeByall(Schedule a2);

	Schedule selecttimeBycode(String schedule_codeString, String weektime1);

    void deleteByCode(String code);

	List<Schedule> selectallBycode(String codenum);

	List<Schedule> selecttimeBycode(Schedule ddddd);

}