package com.cn.web.school.dao;

import com.cn.web.school.po.Record;
import com.cn.web.school.po.Subject;
import com.cn.web.school.po.SubjectExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    int countByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    int deleteByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    int insertSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    List<Subject> selectByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    Subject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") Subject record, @Param("example") SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    int updateByExample(@Param("record") Subject record, @Param("example") SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Wed Jan 27 07:50:38 CST 2016
     */
    int updateByPrimaryKey(Subject record);

	List<Subject> selectstuinfoByCode(Record record);

	List<String> selectcodeBycode(String code);

	List<Subject> selectchoseclass(String sch);
}